import { 
  User, Organization, InstagramAccount, Automation, 
  Lead, Conversation, AIConfiguration, KnowledgeDocument, 
  LinkPage, DigitalProduct, Form, Campaign, AnalyticsSummary 
} from '@/types';

export const DEMO_USER: User = {
  id: 'usr_demo_vamshi',
  name: 'Vamshi Krishna',
  email: 'vamshi@dmflow.ai',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  createdAt: '2026-01-10T10:00:00Z',
};

export const DEMO_ORGANIZATION: Organization = {
  id: 'org_vamshi_digital',
  name: 'Vamshi Digital',
  slug: 'vamshi-digital',
  instagramUsername: 'demo_creator',
  businessCategory: 'Creator & Educator',
  plan: 'PRO',
  createdAt: '2026-01-10T10:05:00Z',
};

export const DEMO_INSTAGRAM_ACCOUNT: InstagramAccount = {
  id: 'ig_acc_demo_1',
  organizationId: DEMO_ORGANIZATION.id,
  instagramUserId: '178414000112233',
  username: 'demo_creator',
  profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  status: 'CONNECTED',
  followersCount: 42800,
  tokenExpiresAt: '2026-11-30T00:00:00Z',
  createdAt: '2026-01-11T12:00:00Z',
  updatedAt: '2026-08-15T09:30:00Z',
};

export const DEMO_AUTOMATIONS: Automation[] = [
  {
    id: 'auto_1_price',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'Instagram Post Comment Auto-DM',
    description: 'When someone comments on post, wait 30s, ask to follow, reply publicly, and send final DM payload.',
    status: 'ACTIVE',
    triggerType: 'INSTAGRAM_COMMENT_KEYWORD',
    triggerKeyword: 'GUIDE',
    postId: 'post_1',
    postCaption: 'Comment "GUIDE" to get my free 10-step AI Instagram Growth Blueprint 🚀👇',
    postImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    autoDmConfig: {
      postId: 'post_1',
      postImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
      postCaption: 'Comment "GUIDE" to get my free 10-step AI Instagram Growth Blueprint 🚀👇',
      postType: 'POST',
      commentCondition: 'CONTAINS',
      keywords: ['GUIDE', 'PRICE', 'COURSE'],
      delaySeconds: 30,
      followMessageText: "Almost there !\n\nPlease visit my profile and tap follow to continue 😁",
      profileUrl: "https://instagram.com/demo_creator",
      visitProfileText: "Visit Profile",
      followingButtonText: "I'm following ✅",
      publicReplyText: "@user Sent you a message! Check it out!",
      finalDmText: `Here are the steps:

Step 1: Upload your Resume in Claude
Step 2: Copy and paste the job description in Claude
Step 3: Paste the below prompt

Prompt:
"I have attached my resume along with the job descriptions for the roles I want to apply for. Your task is to customize my resume for maximum ATS match score."`,
    },
    nodes: [
      { id: '1', type: 'trigger', position: { x: 250, y: 50 }, data: { label: 'Comment contains "GUIDE"', keyword: 'GUIDE' } },
      { id: '2', type: 'message', position: { x: 250, y: 180 }, data: { label: 'Send Follow Prompt DM', messageText: 'Almost there ! Please visit my profile and tap follow to continue 😁' } },
      { id: '3', type: 'ai_response', position: { x: 250, y: 310 }, data: { label: 'Handover to AI Assistant', aiInstructions: 'Answer questions about course duration, pricing, and curriculum.' } },
      { id: '4', type: 'add_tag', position: { x: 250, y: 440 }, data: { label: 'Tag Lead', tagName: 'Guide Prospect', leadScoreAdd: 25 } },
    ],
    executionCount: 342,
    conversionCount: 89,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-08-16T14:20:00Z',
  },
  {
    id: 'auto_2_course',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'Direct DM Keyword: COURSE',
    description: 'Provides instant course info and qualifies user budget.',
    status: 'ACTIVE',
    triggerType: 'INSTAGRAM_DM_KEYWORD',
    triggerKeyword: 'COURSE',
    nodes: [
      { id: '1', type: 'trigger', position: { x: 250, y: 50 }, data: { label: 'DM keyword "COURSE"', keyword: 'COURSE' } },
      { id: '2', type: 'message', position: { x: 250, y: 180 }, data: { label: 'Send Overview', messageText: 'Awesome! We have 2 main tracks: 1) Self-paced AI Playbook ($49), 2) 1-on-1 VIP Strategy ($299). Which one fits your goals best?' } },
      { id: '3', type: 'condition', position: { x: 250, y: 310 }, data: { label: 'User selects VIP?' } },
    ],
    executionCount: 198,
    conversionCount: 45,
    createdAt: '2026-03-15T11:30:00Z',
    updatedAt: '2026-08-14T18:00:00Z',
  },
  {
    id: 'auto_3_guide',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'Free Lead Magnet PDF Download',
    description: 'Captures email in exchange for 10x Instagram AI Guide.',
    status: 'ACTIVE',
    triggerType: 'INSTAGRAM_COMMENT_KEYWORD',
    triggerKeyword: 'GUIDE',
    nodes: [
      { id: '1', type: 'trigger', position: { x: 250, y: 50 }, data: { label: 'Comment contains "GUIDE"', keyword: 'GUIDE' } },
      { id: '2', type: 'message', position: { x: 250, y: 180 }, data: { label: 'Ask Email', messageText: 'Here is your free guide! Please drop your best email so I can send the PDF directly to your inbox.' } },
      { id: '3', type: 'create_lead', position: { x: 250, y: 310 }, data: { label: 'Create Lead in CRM' } },
    ],
    executionCount: 512,
    conversionCount: 230,
    createdAt: '2026-04-10T09:15:00Z',
    updatedAt: '2026-08-17T11:00:00Z',
  },
];

export const DEMO_AI_CONFIG: AIConfiguration = {
  id: 'ai_cfg_demo',
  organizationId: DEMO_ORGANIZATION.id,
  agentName: 'Vamshi AI Assistant',
  businessDescription: 'Vamshi Digital empowers creators, coaches, and brands to automate Instagram DMs, capture high-intent leads, and sell digital courses using AI.',
  websiteUrl: 'https://dmflow.ai',
  tone: 'Friendly',
  instructions: 'Always be encouraging, professional, and helpful. Guide users towards enrolling in the AI Growth Masterclass ($149) or booking a 1-on-1 Consultation ($299). If they ask for discounts, mention code DMFlow30 for 30% off.',
  fallbackMessage: "I'm not completely sure about that detail, but our human team will get right back to you shortly! In the meantime, feel free to check out our free guide.",
  handoffMessage: "Connecting you with Vamshi's team right now! Standard response time is under 15 minutes.",
  status: 'ACTIVE',
};

export const DEMO_KNOWLEDGE_BASE: KnowledgeDocument[] = [
  {
    id: 'kb_1',
    organizationId: DEMO_ORGANIZATION.id,
    title: 'AI Growth Masterclass Curriculum & Price',
    category: 'PRODUCT',
    content: 'The AI Growth Masterclass costs $149 (or $104 with coupon DMFlow30). Includes 8 core modules, 25+ prompt templates, Instagram automation scripts, and lifetime access.',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'kb_2',
    organizationId: DEMO_ORGANIZATION.id,
    title: '1-on-1 Consultation Call Details',
    category: 'PRODUCT',
    content: 'A 60-minute intensive Zoom strategy session with Vamshi to build custom Instagram lead funnels for your business. Price: $299. Booking link: https://dmflow.ai/f/book-call',
    updatedAt: '2026-07-05T14:30:00Z',
  },
  {
    id: 'kb_3',
    organizationId: DEMO_ORGANIZATION.id,
    title: 'Refund & Access Policy',
    category: 'POLICY',
    content: 'All digital products come with a 14-day money-back guarantee. Instant access is delivered via email right after payment completion.',
    updatedAt: '2026-06-12T09:00:00Z',
  },
];

export const DEMO_LEADS: Lead[] = [
  {
    id: 'lead_rahul',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'Rahul Sharma',
    instagramUsername: 'rahul_tech_coach',
    email: 'rahul.sharma@example.com',
    phone: '+91 98765 43210',
    company: 'Rahul Coaching Academy',
    budget: '$500 - $1,000',
    status: 'QUALIFIED',
    leadScore: 88,
    tags: ['Hot Lead', 'Masterclass Prospect', 'High Intent'],
    notes: 'Interested in automating DM replies for his 50k Instagram followers.',
    customFields: [
      { fieldId: 'cf_niche', fieldName: 'Niche', value: 'EdTech / Coaching' },
      { fieldId: 'cf_goal', fieldName: 'Primary Goal', value: 'Course Sales' },
    ],
    createdAt: '2026-08-10T14:20:00Z',
    lastInteractionAt: '2026-08-17T15:30:00Z',
  },
  {
    id: 'lead_sneha',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'Sneha Patel',
    instagramUsername: 'sneha_designs',
    email: 'sneha@designstudio.io',
    company: 'Sneha Design Lab',
    budget: '$1,000+',
    status: 'CONVERTED',
    leadScore: 95,
    tags: ['Converted', 'VIP Client'],
    notes: 'Purchased 1-on-1 Consultation package.',
    customFields: [
      { fieldId: 'cf_niche', fieldName: 'Niche', value: 'UI/UX Design' },
    ],
    createdAt: '2026-08-01T09:10:00Z',
    lastInteractionAt: '2026-08-16T11:45:00Z',
  },
  {
    id: 'lead_arjun',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'Arjun Mehta',
    instagramUsername: 'arjun_fitness',
    email: 'arjun@fitcorp.com',
    status: 'INTERESTED',
    leadScore: 65,
    tags: ['Warm Lead', 'Fitness Niche'],
    notes: 'Asked about gym lead generation setup.',
    createdAt: '2026-08-12T16:00:00Z',
    lastInteractionAt: '2026-08-15T18:20:00Z',
  },
  {
    id: 'lead_priya',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'Priya Roy',
    instagramUsername: 'priya_realty',
    email: 'priya@realestatehub.com',
    phone: '+91 99887 76655',
    status: 'NEW',
    leadScore: 40,
    tags: ['Real Estate', 'New Lead'],
    notes: 'Downloaded free Instagram PDF guide.',
    createdAt: '2026-08-17T10:00:00Z',
    lastInteractionAt: '2026-08-17T10:05:00Z',
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_rahul',
    organizationId: DEMO_ORGANIZATION.id,
    instagramUsername: 'rahul_tech_coach',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    leadId: 'lead_rahul',
    status: 'ACTIVE',
    aiMode: 'ACTIVE',
    lastMessageText: 'Can I get a discount if I enroll today for the Masterclass?',
    lastMessageAt: '2026-08-17T15:30:00Z',
    unreadCount: 1,
    messages: [
      { id: 'm1', conversationId: 'conv_rahul', sender: 'INSTAGRAM_USER', text: 'PRICE', timestamp: '2026-08-17T15:20:00Z', delivered: true },
      { id: 'm2', conversationId: 'conv_rahul', sender: 'SYSTEM', text: 'Hey Rahul 👋 Thanks for commenting! Here is the direct link to our AI Masterclass: https://dmflow.ai/p/ai-masterclass', timestamp: '2026-08-17T15:20:05Z', delivered: true },
      { id: 'm3', conversationId: 'conv_rahul', sender: 'INSTAGRAM_USER', text: 'Does it cover Instagram DM automation triggers?', timestamp: '2026-08-17T15:25:00Z', delivered: true },
      { id: 'm4', conversationId: 'conv_rahul', sender: 'AI_AGENT', text: 'Yes, absolutely! Module 4 covers setting up comment-to-DM keywords, visual workflows, and lead scoring step-by-step.', timestamp: '2026-08-17T15:25:03Z', delivered: true },
      { id: 'm5', conversationId: 'conv_rahul', sender: 'INSTAGRAM_USER', text: 'Can I get a discount if I enroll today for the Masterclass?', timestamp: '2026-08-17T15:30:00Z', delivered: true },
    ],
  },
  {
    id: 'conv_sneha',
    organizationId: DEMO_ORGANIZATION.id,
    instagramUsername: 'sneha_designs',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    leadId: 'lead_sneha',
    status: 'ACTIVE',
    aiMode: 'PAUSED',
    lastMessageText: 'Thank you Vamshi! Looking forward to our call tomorrow.',
    lastMessageAt: '2026-08-16T11:45:00Z',
    unreadCount: 0,
    messages: [
      { id: 'm10', conversationId: 'conv_sneha', sender: 'INSTAGRAM_USER', text: 'Hi, I want to book a 1-on-1 consultation for my design studio.', timestamp: '2026-08-16T11:30:00Z', delivered: true },
      { id: 'm11', conversationId: 'conv_sneha', sender: 'HUMAN_AGENT', text: 'Hey Sneha! Great to connect. You can pick any available slot here: https://dmflow.ai/f/book-call', timestamp: '2026-08-16T11:35:00Z', delivered: true },
      { id: 'm12', conversationId: 'conv_sneha', sender: 'INSTAGRAM_USER', text: 'Thank you Vamshi! Looking forward to our call tomorrow.', timestamp: '2026-08-16T11:45:00Z', delivered: true },
    ],
  },
];

export const DEMO_LINK_PAGE: LinkPage = {
  id: 'lp_demo',
  organizationId: DEMO_ORGANIZATION.id,
  username: 'demo_creator',
  title: 'Vamshi Krishna | Instagram AI & Automation',
  bio: 'Helping creators & brands turn followers into paid customers with automated Instagram DMs & AI agents. 🚀',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  theme: 'glass',
  published: true,
  viewsCount: 14200,
  clicksCount: 5180,
  blocks: [
    {
      id: 'b1',
      type: 'HEADER',
      title: 'Featured Programs & Offers',
      enabled: true,
      order: 1,
    },
    {
      id: 'b2',
      type: 'PRODUCT',
      title: '🎓 AI Growth Masterclass (30% OFF)',
      content: 'Master Instagram DM Funnels & AI lead capture in 8 modules.',
      url: '/p/ai-masterclass',
      enabled: true,
      order: 2,
    },
    {
      id: 'b3',
      type: 'PRODUCT',
      title: '⚡ 1-on-1 VIP Strategy Session',
      content: '60-min intensive execution call to double your conversion rate.',
      url: '/p/vip-consultation',
      enabled: true,
      order: 3,
    },
    {
      id: 'b4',
      type: 'FORM',
      title: '📩 Download Free 10x Instagram Playbook',
      content: 'Get our battle-tested DM templates & automation workflows.',
      url: '/f/free-playbook',
      enabled: true,
      order: 4,
    },
    {
      id: 'b5',
      type: 'SOCIALS',
      title: 'Connect With Me Everywhere',
      enabled: true,
      order: 5,
      metadata: {
        instagram: 'https://instagram.com/demo_creator',
        youtube: 'https://youtube.com/@demo_creator',
        twitter: 'https://x.com/demo_creator',
      },
    },
  ],
};

export const DEMO_PRODUCTS: DigitalProduct[] = [
  {
    id: 'prod_masterclass',
    organizationId: DEMO_ORGANIZATION.id,
    title: 'AI Growth Masterclass',
    description: 'Learn how to build 24/7 automated Instagram sales engines using AI and DM flow triggers.',
    price: 149,
    currency: 'USD',
    type: 'Course',
    productUrl: 'https://dmflow.ai/p/ai-masterclass',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    salesCount: 89,
    revenue: 13261,
    status: 'ACTIVE',
  },
  {
    id: 'prod_consultation',
    organizationId: DEMO_ORGANIZATION.id,
    title: '1-on-1 VIP Strategy Session',
    description: 'Personalized Zoom session to setup your Instagram leads pipeline.',
    price: 299,
    currency: 'USD',
    type: 'Consultation',
    productUrl: 'https://dmflow.ai/p/vip-consultation',
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&auto=format&fit=crop&q=80',
    salesCount: 28,
    revenue: 8372,
    status: 'ACTIVE',
  },
  {
    id: 'prod_playbook',
    organizationId: DEMO_ORGANIZATION.id,
    title: 'Instagram Automation Scripts PDF',
    description: 'Plug-and-play DM script templates for comment keywords.',
    price: 29,
    currency: 'USD',
    type: 'Digital',
    productUrl: 'https://dmflow.ai/p/scripts-pdf',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&auto=format&fit=crop&q=80',
    salesCount: 142,
    revenue: 4118,
    status: 'ACTIVE',
  },
];

export const DEMO_FORMS: Form[] = [
  {
    id: 'f_consultation',
    organizationId: DEMO_ORGANIZATION.id,
    title: 'Book a Strategy Call',
    description: 'Fill out this quick questionnaire to reserve your 1-on-1 slot.',
    fields: [
      { id: 'f1', label: 'Full Name', fieldType: 'TEXT', placeholder: 'Rahul Sharma', required: true },
      { id: 'f2', label: 'Instagram Handle', fieldType: 'TEXT', placeholder: '@yourhandle', required: true },
      { id: 'f3', label: 'Work Email', fieldType: 'EMAIL', placeholder: 'name@company.com', required: true },
      { id: 'f4', label: 'Monthly Instagram Traffic', fieldType: 'SELECT', required: true, options: ['Under 10k', '10k - 50k', '50k - 200k', '200k+'] },
      { id: 'f5', label: 'Primary Goal', fieldType: 'TEXT', placeholder: 'Convert post comments into course sales', required: false },
    ],
    submissionsCount: 42,
    createdAt: '2026-03-01T10:00:00Z',
  },
];

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_1',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'AI Masterclass August Promo',
    type: 'Course Promo',
    description: 'Instagram reel comment campaign driving keyword PRICE to checkout page.',
    ctaText: 'Comment PRICE on Instagram',
    linkUrl: 'https://dmflow.ai/p/ai-masterclass',
    views: 45200,
    clicks: 6800,
    leadsCaptured: 342,
    status: 'ACTIVE',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'camp_2',
    organizationId: DEMO_ORGANIZATION.id,
    name: 'Free Lead Magnet PDF Blast',
    type: 'Lead Magnet',
    description: 'Comment GUIDE campaign to capture emails for newsletter.',
    ctaText: 'Comment GUIDE on Instagram',
    linkUrl: 'https://dmflow.ai/f/free-playbook',
    views: 89000,
    clicks: 12400,
    leadsCaptured: 512,
    status: 'ACTIVE',
    createdAt: '2026-07-15T09:00:00Z',
  },
];

export const DEMO_ANALYTICS: AnalyticsSummary = {
  totalLeads: 1284,
  newLeads7d: 148,
  totalConversations: 3490,
  aiResponsesCount: 8920,
  conversionRate: 18.4,
  revenue: 25751,
  linkViews: 14200,
  formSubmissions: 412,
  chartData: [
    { date: 'Aug 11', leads: 18, conversations: 42, revenue: 450 },
    { date: 'Aug 12', leads: 24, conversations: 58, revenue: 780 },
    { date: 'Aug 13', leads: 19, conversations: 51, revenue: 299 },
    { date: 'Aug 14', leads: 32, conversations: 85, revenue: 1149 },
    { date: 'Aug 15', leads: 28, conversations: 74, revenue: 890 },
    { date: 'Aug 16', leads: 41, conversations: 110, revenue: 1490 },
    { date: 'Aug 17', leads: 38, conversations: 98, revenue: 1240 },
  ],
};
